export type Enums = {
  application_status: "draft" | "submitted" | "under_review" | "approved" | "declined"
  audit_action: "INSERT" | "UPDATE" | "DELETE" | "SOFT_DELETE"
  event_category:
    | "Fashion Show"
    | "Gala"
    | "Workshop"
    | "Exhibition"
    | "Conference"
    | "Networking"
    | "Awards_Ceremony"
    | "Runway_Show"
    | "Masterclass"
    | "Pop_Up_Shop"
    | "VIP_Reception"
    | "Industry_Mixer"
    | "Designer_Showcase"
    | "Trend_Presentation"
  event_status: "draft" | "published" | "completed" | "cancelled"
  media_status: "draft" | "published"
  media_type: "gallery" | "highlights" | "promotional"
  message_status: "sent" | "delivered" | "read"
  notification_category: "events" | "tickets" | "messages" | "marketing"
  notification_type: "event_update" | "ticket_purchase" | "message" | "system"
  payment_status: "pending" | "completed" | "failed" | "refunded"
  profile_status: "incomplete" | "complete"
  sponsor_status: "active" | "inactive"
  sponsorship_status: "pending" | "approved" | "active" | "completed"
  sponsorship_type: "physical" | "digital" | "hybrid"
  ticket_status: "available" | "reserved" | "purchased" | "cancelled"
  ticket_tier: "general" | "vip"
  ticket_type_status: "active" | "inactive" | "sold_out"
  user_role: "admin" | "model" | "designer" | "sponsor" | "visitor"
}